//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masood_lab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library_systemEntities1 : DbContext
    {
        public Library_systemEntities1()
            : base("name=Library_systemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_librarian> tbl_librarian { get; set; }
        public virtual DbSet<tblBooksCategory> tblBooksCategories { get; set; }
        public virtual DbSet<tblBooksMember> tblBooksMembers { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblNewBooks_registration> tblNewBooks_registration { get; set; }
        public virtual DbSet<tblNewMembers_registration> tblNewMembers_registration { get; set; }
    }
}
