//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masood_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_librarian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_librarian()
        {
            this.tblLogins = new HashSet<tblLogin>();
        }
    
        public int lib_id { get; set; }
        public string lib_username { get; set; }
        public string lib_password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phonenumber { get; set; }
        public string NIC { get; set; }
        public string ImagePath { get; set; }
        public string repeat_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogin> tblLogins { get; set; }
    }
}
