//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masood_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooksMember
    {
        public int registrationID { get; set; }
        public int BookID { get; set; }
        public int MemberID { get; set; }
        public string IssuedDate { get; set; }
        public string ExpiryDate { get; set; }
    
        public virtual tblNewBooks_registration tblNewBooks_registration { get; set; }
        public virtual tblNewMembers_registration tblNewMembers_registration { get; set; }
    }
}
