//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masood_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewMembers_registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNewMembers_registration()
        {
            this.tblBooksMembers = new HashSet<tblBooksMember>();
            this.tblLogins = new HashSet<tblLogin>();
        }
    
        public int memberID { get; set; }
        public string member_username { get; set; }
        public string FullName { get; set; }
        public string Phonenumber { get; set; }
        public string NIC { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Date_of_birth { get; set; }
        public string Gender { get; set; }
        public string member_Password { get; set; }
        public string RepeatPassword { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBooksMember> tblBooksMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLogin> tblLogins { get; set; }
    }
}
