//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masood_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewBooks_registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNewBooks_registration()
        {
            this.tblBooksMembers = new HashSet<tblBooksMember>();
        }
    
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string BookAuthor { get; set; }
        public string BookPublisher { get; set; }
        public string BookPrice { get; set; }
        public int BookCategory { get; set; }
        public string ImagePath { get; set; }
    
        public virtual tblBooksCategory tblBooksCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBooksMember> tblBooksMembers { get; set; }
    }
}
